### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/action-conventional-commits#1]
Another special request that we should accommodate because this is when I'm updating the README.md from the GitHub UI.

https://github.com/ubiquity/devpool-directory/commit/538fe692775e6793aa6b01911bd256830656c924

**Comment by PhantomCracker** [comment]
@pavlovcik do we still need to update the README.md file? I see that is pretty similar with what you have provided

**Comment by 0x4007** [comment]
No its to enable support for our conventional commits for that commit message. "Update README.md"

**Comment by PhantomCracker** [comment]
Here is the proof of testing: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5421867225
I will remove the testing file from the pull request

**Comment by 0x4007** [comment]
> Here is the proof of testing: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5421867225
> I will remove the testing file from the pull request

Thank you for this.

**Comment by 0x4007** [comment]
https://github.com/ubiquity/ubiquity-dollar/actions/runs/5480174450/jobs/9983001781

> Commit messages:
>   🚩 Update conventional-commits.yml
> Error: 🚫 According to the conventional-commits specification, some of the commit messages are not valid.

**Comment by 0x4007** [comment]
I just realized that it's running `dist/main/index.js` and we aren't automatically updating that.

**Comment by PhantomCracker** [comment]
> I just realized that it's running `dist/main/index.js` and we aren't automatically updating that.

Oh I see, then should I also take the new issue to fix this? 
Please add time label and assign it to me when you can, thank you!

**Comment by 0x4007** [comment]
#5
