### ISSUE TITLE
"Initial commit" commit message does not pass conventional commits

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/action-conventional-commits#3]
It is unfortunate that when creating a new repository from this template, the first commit will always fail CI. Is there a solution to change either the default commit message, or should we modify [our version of conventional commits](https://github.com/ubiquity/action-conventional-commits) to explicitly support the "Initial commit" commit message?

https://github.com/ubiquity/ubiquibot-sandbox/commit/6d5006d4594aaf4f79bab6f1767b29cce987a921

**Comment by Steveantor** [comment]
Should update the conventional commits

**Comment by PhantomCracker** [comment]
Can't the bounty:
<img width="603" alt="Screenshot 2023-07-05 at 12 45 04" src="https://github.com/ubiquity/action-conventional-commits/assets/5438246/90830eda-eb3e-4d38-b848-c8fbe6cb7c93">
Thanks

**Comment by 0x4007** [comment]
Are you on the right network? Can you share an error from the console? I'm going to update the dApp now with the last few weeks of changes.

**Comment by PhantomCracker** [comment]
Sure:
<img width="1605" alt="Screenshot 2023-07-05 at 13 21 11" src="https://github.com/ubiquity/action-conventional-commits/assets/5438246/7b742c8b-abd0-4c8c-9c3c-6158ee26a272">

**Comment by 0x4007** [comment]
Can you try using the latest commit's instance of the dApp for now? Based on your screenshot I believe that you are connected to Ethereum Mainnet and this payment permit is for Gnosis Chain. 

We just added the new query parameter, `?network=100` to tell the dApp to tell you to change networks.

https://7f047d5d.ubiquity-bounty-claims.pages.dev/?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjUwMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI4MDQ4MjcyOTI4NDM0NDY3NTgwNDAwNzI2MjQ0MzkyOTEyNTEyNDk1MDkwODQ3Nzc4MzI2NTQ0MzkzNjYxNjI2MjUyMDI3NDMwMjgzNyIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4Q0FDMEE4Y0Y0Y2M3MDczYjA0MGM3ZmU2MzI4RGE3ZjIyOUFGNDBBNiIsInJlcXVlc3RlZEFtb3VudCI6IjI1MDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHgzZGVjZGExYTI4MjIyZmViNmI4MGM4YTIwYzgxMGI2YTUzOTMyOWUzZDhmMDZhZTZmMDA0ODgxNDkzNTExZjNiMDlmMjlkMTkwYzg3MTg3ZTQ2YjFmMGY2OGVmMTNiZTI2ZDEzMDJhYjZiMDNkMDE1MmU1YjcxYzA4ZWE2ZTU3NDFiIn0=&network=100

**Comment by PhantomCracker** [comment]
<img width="550" alt="Screenshot 2023-07-05 at 13 25 18" src="https://github.com/ubiquity/action-conventional-commits/assets/5438246/ea67687f-a4f5-4e23-8d78-4505706444c8">

**Comment by 0x4007** [comment]
Yes, please switch to Gnosis Chain to claim the 25 WXDAI on Gnosis Chain.
