### ISSUE TITLE
`tsx` runtime to invoke source code

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/action-conventional-commits#5]
We should delete the `dist/` folder, and `action.yml` should invoke `tsx` as a runtime to run the `src/` TypeScript code natively, ensuring that we're always up-to-date with the code that we're running. 

> I just realized that it's running `dist/main/index.js` and we aren't automatically updating that.

_Originally posted by @pavlovcik in https://github.com/ubiquity/action-conventional-commits/issues/1#issuecomment-1624317707_

**Comment by b4s36t4** [comment]
Can I pick this?!

**Comment by 0x4007** [comment]
You should use the assign command

**Comment by PhantomCracker** [comment]
@pavlovcik I am trying to look for different situations instead of using deprecated "command", but can I ask why do we need to remove dist/index.js and use src/main.ts?

> To ensure your JavaScript actions are compatible with all GitHub-hosted runners (Ubuntu, Windows, and macOS), the packaged JavaScript code you write should be pure JavaScript and not rely on other binaries. JavaScript actions run directly on the runner and use binaries that already exist in the runner image.

Also, action.yml is some kind of metadata for actions and they need a main input file (this file needs to be pure js file)

**Comment by 0x4007** [comment]
> why do we need to remove dist/index.js and use src/main.ts?

It adds a lot of additional complexity to maintaining our codebase if the developers must change the source code AND change the compiled files. We tried manually but developers rarely did both. We tried automating but there were issues around GitHub Actions automatically building and committing the compiled files to the repository (merge conflicts every time a developer wanted to update the code.)

Instead I say that we dont deal with compiling the files and just run the source code directly. It makes things simpler.

> Also, action.yml is some kind of metadata for actions and they need a main input file (this file needs to be pure js file)

We can consider a hard coded input file that executes `process.exec` using `tsx` to run the source code natively?

**Comment by PhantomCracker** [comment]
@pavlovcik issue solved, PR ready for review

**Comment by PhantomCracker** [comment]
Any news @pavlovcik ?

**Comment by 0x4007** [comment]
I left a review!

**Comment by rndquu** [comment]
@PhantomCracker conventional commits CI action is [broken](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5681833717/job/15398837130?pr=735) after this [PR](https://github.com/ubiquity/action-conventional-commits/pull/7), pls fix

**Comment by PhantomCracker** [comment]
> @PhantomCracker conventional commits CI action is [broken](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5681833717/job/15398837130?pr=735) after this [PR](https://github.com/ubiquity/action-conventional-commits/pull/7), pls fix

ok, let me check and work in progress

**Comment by PhantomCracker** [comment]
@rndquu please check this PR: https://github.com/ubiquity/action-conventional-commits/pull/9

**Comment by PhantomCracker** [comment]
The pull request will be merged soon.
